apiVersion: apps/v1
kind: Deployment
metadata:
  name: oms-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oms-app
  template:
    metadata:
      labels:
        app: oms-app
    spec:
      containers:
        - name: oms-app
          image: semicolon/oms:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: oms-config
            - secretRef:
                name: oms-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: oms-app
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: oms-app
