apiVersion: v1
kind: ConfigMap
metadata:
  name: oms-config
data:
  SPRING_PROFILES_ACTIVE: "dev"
  DB_HOST: "oms-postgres"
  DB_PORT: "5432"
  DB_NAME: "oms_db"
  REDIS_HOST: "oms-redis"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "oms-kafka:9092"
