apiVersion: v1
kind: Secret
metadata:
  name: oms-secret
type: Opaque
stringData:
  DB_USERNAME: "oms_user"
  DB_PASSWORD: "oms_pass"
  JWT_SECRET: "productionSecretKeyThatShouldBeChangedInRealDeployment2026"
